### ISSUE TITLE
A single character encoded in UTF-8 can be more than a byte long

### ISSUE THREAD

**Issue by pauliax** [BitGuildPlatform/Contracts#11]
AvatorOperator.sol

```
  modifier nameValid(string _name){
    bytes memory nameBytes = bytes(_name);
    require(nameBytes.length > 0);
    require(nameBytes.length < 16);
```

You use bytes(str).length to check string length, so you should know that encoded strings can differ in length, for instance, a single character encoded in UTF-8 can be more than a byte long.

**Comment by shaokun11** [comment]
@pauliax  I think it needn't worry because the name can only create from '0-9a-zA-Z_'.Thanks your suggestion.

**Comment by vernon99** [comment]
Yeah, a bit dirty, but is fine in our case.
