### ISSUE TITLE
Manually update the length after deleting item from the array

### ISSUE THREAD

**Issue by pauliax** [BitGuildPlatform/Contracts#12]
AvatarItemToken.sol

```
    avatarItems[tokenIndex] = avatarItems[avatarItems.length.sub(1)];
    delete avatarItems[avatarItems.length.sub(1)];
```

Now the length of the array is not reduced, just the last element becomes empty. To fully remove an item you need to manually update the length property:
`avatarItems.length--;`

**Comment by shaokun11** [comment]
@pauliax  Thanks your opinions. At this version, I use the avatarItems.length to generate token id , if I really reduce the length, which will cause duplicate token id. so I just swap burned item position for last item position.
