### ISSUE TITLE
Wrong price in PLAT

### ISSUE THREAD

**Issue by pauliax** [BitGuildPlatform/Contracts#9]
BitizensIGO.sol

```
 /// @dev Constructor. Create hardcoded set info with price
    constructor() public {
        // Price in PLAT
        setIdToPrice[16] = 180000 * 1e18;      //  3.0 Eth
        setIdToPrice[17] = 60000 * 1e18;       //  0.5 Eth
```

The calculation for setIdToPrice[17] is wrong or the comment is misleading. If 180000 * 1e18 is 3 Eth, then 0.5 Eth should be 30000 * 1e18.

**Comment by vernon99** [comment]
@calvinmd can you take a look?

**Comment by calvinmd** [comment]
Yeah, the comment wasn't updated. Verified the price is set correctly. Thanks.
